### ISSUE TITLE
게임 종료 상태시 모달 창으로 종료 알리기

### ISSUE THREAD

**Issue by flowjiyun** [august-thirty-first/frontend#86]
## 기능 명세
- 게임 종료 상태
    - 정상적 종료 : 스코어에 따른 게임 종료
    - 비정상 종료 : 한명이 나갔을 때 

- 게임 승패를 모달 창에 적절히 표시
- 홈으로가기 버튼 만들기
    - 버튼 클릭 시 홈으로 라우팅
    - 클라이언트에서 소켓 끊기
- [x] 옵션창에서 gameOverInOptionPage 이벤트 받고 모달창 띄우는 기능 추가
- [ ] 게임에서도 validate 체크해야 함
- [ ] multipleLadderConnect 받아서 홈으로 라우트
## 예상 시간

**Comment by yeseulgangahan** [comment]
history 안 넘어오는 문제 확인 필요

**Comment by yeseulgangahan** [comment]
얍
